name: cron job

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm start
